version: '3.7'

services:

  MySQL:
    image: mysql:8.0.31
    hostname: MySQL
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Password12!
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass

  Postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass

  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    ports:
      - '9999:9999'