version: '3'

services:

  MySQL:
    image: mysql:latest
    hostname: MySQL
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: Password12!
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: app

  Postgres:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      MYSQL_ROOT_PASSWORD: Password12!
      POSTGRES_USER: app
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app

volumes:
  pgdata: